### ISSUE TITLE
hyperlink in caption?

### ISSUE THREAD

**Issue by vecjh** [trilbymedia/grav-plugin-image-captions#18]
Hi, how to add hyperlink to the caption with this plugin? It's doesn't seem to interpret html tags in the caption.

**Comment by rhukster** [comment]
HTML is not supported in title or alt takes, so i'm afraid not.

**Comment by fspin** [comment]
Hi @rhukster, I re-open the issue, because indeed on `alt` and on `title` you can't add HTML, but the [figcaption's permitted content](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption#technical_summary) is [flow content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#flow_content) so, adding an hyperlink in the caption's field of the image's metadata, should render correctly. 

It will be great if we can work this out with a template (as mentioned in https://github.com/trilbymedia/grav-plugin-image-captions/issues/6). 

Please, let me know if a pull request with the template will be appreciated. Although I'm not very versed in php, I think I could do something in here.

**Comment by rhukster** [comment]
A PR is always appreciated! Cheers.
